### ISSUE TITLE
Windows: Crowding and Overlapping (iPhone and Android - Horizontal)

### ISSUE THREAD

**Issue by PilotFishHK** [ancaipen/Provia#60] opened 2022-03-20 22:52 UTC
**iPhone and Android: Horizontal Orientation**

**All Windows Brands pages have an overlapping green rule over the main image and text and images that are overlapping: **

**Examples:**

https://provia.proviaserver-v2.com/doors/entry-doors/victorian

iPhone: 
![image](https://user-images.githubusercontent.com/101943507/159189324-c410f30a-1fed-44d5-a8fa-d5f97035ade1.png)
----------------------
Andriod: 
https://provia.proviaserver-v2.com/windows/victorian

----------------------
![image](https://user-images.githubusercontent.com/101943507/159189336-d31456b7-ae3c-4162-90eb-1242b6ddf68b.png)

----------------------
![image](https://user-images.githubusercontent.com/101943507/159189348-b3457a3d-8cdb-41a0-8deb-4d4adbf0228b.png)

----------------------
![image](https://user-images.githubusercontent.com/101943507/159189355-3d5312da-2982-48c2-bcd7-5c7b7be049a6.png)

----------------------

![image](https://user-images.githubusercontent.com/101943507/159189359-a27decf4-6e14-4b7c-811d-f2b90c7b6e63.png)

----------------------

https://provia.proviaserver-v2.com/windows/craftsman 

----------------------

![image](https://user-images.githubusercontent.com/101943507/159189366-8b7b6a4b-b160-405d-8d39-40b250407ec3.png)

----------------------

https://provia.proviaserver-v2.com/windows/classic-colonial

----------------------

![image](https://user-images.githubusercontent.com/101943507/159189374-9aa83de2-449f-45a5-a335-4194740b101e.png)

----------------------

https://provia.proviaserver-v2.com/windows/modern 

----------------------

![image](https://user-images.githubusercontent.com/101943507/159189384-4d162401-3a8a-43d8-8b8b-b0f4936964a9.png)

**Comment by SeanIsAtWork** [comment] 2022-03-21 19:25
This is caused by the header sections' maximum height being too small, this should be fixed across all instances.

**Closed by SeanIsAtWork** 2022-03-21 19:25 UTC
