### ISSUE TITLE
Session expires when I interact with the logout button in the menu

### ISSUE THREAD

**Issue by SeanIsAtWork** [ancaipen/Provia#370] opened 2022-04-27 19:59 UTC
![image](https://user-images.githubusercontent.com/95431522/165620911-1038a2c7-246f-4370-acf4-72489196ce94.png)
I get logged out and told that my session has expired whenever i mess around with the menu. I intentionally triggered this when hovering on and off the logout button in the menu of both the regular site and on the design center/portfolio

**Comment by SeanIsAtWork** [comment] 2022-04-28 13:16
Confirming that this happens every time I just hover over the logout button (default ultimate member menu item) from either menu

**Comment by ancaipen** [comment] 2022-04-28 17:03
@SeanIsAtWork @ncaipen - This maybe caused by the new auto-save.  I removed this and I can't reproduce this issue.  I'm guessing this might be the issue.  Can you both see if this issue still exists?

**Comment by plaugs** [comment] 2022-04-29 18:02
![Capture](https://user-images.githubusercontent.com/831625/165997937-92bd354f-559a-46ed-84d4-1957162610f0.JPG)

Did some tests and noticed that during the mouseover DOM event, a redirect is triggered from 
https://provia.proviaserver-v2.com/wp-content/plugins/elementor-pro/assets//lib/instant-page/instant-page.min.js?ver=3.6.4

**Comment by ncaipen** [comment] 2022-04-29 19:50
I opened a ticket with Ultimate Member.  I'm hoping they will be able to give some insight.  I will update when I hear back.

**Comment by SeanIsAtWork** [comment] 2022-05-03 17:45
Looks like this isnt a problem anymore, at least for me

**Comment by ncaipen** [comment] 2022-05-03 17:49
Fixed for me too!

**Comment by ancaipen** [comment] 2022-05-04 13:25
@SeanIsAtWork @jenkline @ncaipen @PilotFish3447 - Nice!  I'm closing this item.  If we see this issue again we can open it again.  Thanks!

**Closed by ancaipen** 2022-05-04 13:25 UTC
Labels: bug
