### ISSUE TITLE
Vision Board delete feature

### ISSUE THREAD

**Issue by jenkline** [ancaipen/Provia#355] opened 2022-04-27 13:34 UTC
Sean and I cannot find a way to delete saved vision boards. Can this be an added feature? It seems like something we'd want to make available before launch.

**Comment by ancaipen** [comment] 2022-05-01 19:57
@jenkline @SeanIsAtWork - This functionality has been added (see below).  Note that boards are "soft" deleted, this means that the data is still available in the back end and we can restore it if needed (although it is a manual database update at this time).  

There will need to be some css tweaks as well to allow for the x to overlay nicely, etc but it does appear to working as intended.  Please test and let me know if this is working.  Thanks!

![image](https://user-images.githubusercontent.com/43222107/166162391-439bea3e-c26b-4bfe-b725-393b1d1b93b7.png)

![image](https://user-images.githubusercontent.com/43222107/166162451-13ef780b-f5ab-44a1-ab06-41dac79b18a5.png)

**Comment by jenkline** [comment] 2022-05-02 13:20
@ancaipen It is working for me!

**Comment by PilotFish3447** [comment] 2022-05-02 19:57
Works for me. I'm closing this out.

**Closed by PilotFish3447** 2022-05-02 19:57 UTC
Labels: enhancement, CSS issue, ready for retest
