### ISSUE TITLE
WTB not working for me

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#322] opened 2022-04-07 13:09 UTC
The WTB is still not working for me.  Nothing happens when I click Get Results.

**Comment by ncaipen** [comment] 2022-04-18 20:47
@PilotFish3447 - I'm closing this issue as it looks like this was caused by sucuri which was resolved.  If this is still a problem please reopen.  Thanks!

**Closed by ncaipen** 2022-04-18 20:47 UTC
